import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import readline from 'readline';

function generateRandomHex(bytes: number): string {
  return crypto.randomBytes(bytes).toString('hex');
}

function generateRandomBase64(bytes: number): string {
  return crypto.randomBytes(bytes).toString('base64');
}

async function runWizard() {
  console.log('\n======================================================');
  console.log('  ⚡ CRYPTO E-COMMERCE TEMPLATE SETUP WIZARD ⚡');
  console.log('======================================================\n');
  console.log('This wizard generates cryptographically secure secrets,');
  console.log('configures your environment, and prepares the database.\n');

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const prompt = (query: string, defaultValue: string): Promise<string> => {
    return new Promise((resolve) => {
      rl.question(`${query} [${defaultValue}]: `, (ans) => {
        resolve(ans.trim() || defaultValue);
      });
    });
  };

  const storeName = await prompt('Enter your Store Name', 'Crypto Commerce');
  const storeDesc = await prompt('Enter your Store Description', 'Private, Self-Custodial Crypto E-Commerce');
  const storeUrl = await prompt('Enter your Site URL', 'http://localhost:3000');
  
  rl.close();

  const envPath = path.join(process.cwd(), '.env');
  const envLocalPath = path.join(process.cwd(), '.env.local');

  const authSecret = generateRandomBase64(32);
  const payTokenSecret = generateRandomHex(32);
  const cronSecret = generateRandomHex(24);

  const envContent = `# ==============================================================================
# CRYPTO E-COMMERCE CONFIGURATION — GENERATED BY SETUP WIZARD
# ==============================================================================

# Database Connection (SQLite for dev, PostgreSQL for production)
DATABASE_URL="file:./dev.db"

# Public Branding & Metadata
NEXT_PUBLIC_SITE_NAME="${storeName}"
NEXT_PUBLIC_SITE_DESCRIPTION="${storeDesc}"
NEXT_PUBLIC_SITE_URL="${storeUrl}"

# Core Security Secrets (Cryptographically Generated)
AUTH_SECRET="${authSecret}"
PAY_TOKEN_SECRET="${payTokenSecret}"
CRON_SECRET="${cronSecret}"

# Feature Flags
ENABLE_RESELLER="true"
ENABLE_AFFILIATES="true"
ENABLE_MARKETING="true"
ALLOW_GUEST_CHECKOUT="true"

# Cryptocurrency Payment Gateway
CRYPTO_PAYMENTS_ENABLED="true"

# External Explorer APIs (Optional)
# COINGECKO_API_KEY=""
# ETHERSCAN_API_KEY=""
# SOLANA_RPC_URL=""
# HELIUS_API_KEY=""

# Cloudflare R2 / S3 Storage (Optional)
# R2_ACCOUNT_ID=""
# R2_ACCESS_KEY_ID=""
# R2_SECRET_ACCESS_KEY=""
# R2_BUCKET_NAME=""
# R2_PUBLIC_DOMAIN=""

# Transactional Email (Resend)
# RESEND_API_KEY=""
# RESEND_FROM="no-reply@yourdomain.com"
`;

  fs.writeFileSync(envLocalPath, envContent);
  if (!fs.existsSync(envPath)) {
    fs.writeFileSync(envPath, envContent);
  }

  console.log('\n🔒 Generated cryptographically secure keys:');
  console.log(`   AUTH_SECRET:      ${authSecret.substring(0, 8)}... (256-bit base64)`);
  console.log(`   PAY_TOKEN_SECRET: ${payTokenSecret.substring(0, 8)}... (256-bit hex)`);
  console.log(`   CRON_SECRET:      ${cronSecret.substring(0, 8)}... (192-bit hex)`);
  console.log('\n📁 Written environment files: .env and .env.local');
  console.log('\n🚀 Next Steps:');
  console.log('   1. Run "npm run db:push" (or "bun run db:push") to create SQLite database');
  console.log('   2. Run "npm run db:seed" (or "bun run db:seed") to populate starter catalog & admin');
  console.log('   3. Run "npm run dev" to launch your store!\n');
}

runWizard().catch(console.error);
